FROM python:3.7

ARG STAGE
ARG TENANT
ARG REDSHIFT_IAM_ROLE
ARG REDSHIFT_HOST
ARG REDSHIFT_USERNAME
ARG REDSHIFT_PASSWORD

ENV STAGE=$STAGE
ENV TENANT=$TENANT
ENV REDSHIFT_IAM_ROLE=$REDSHIFT_IAM_ROLE
ENV REDSHIFT_HOST=$REDSHIFT_HOST
ENV REDSHIFT_USERNAME=$REDSHIFT_USERNAME
ENV REDSHIFT_PASSWORD=$REDSHIFT_PASSWORD


COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
